// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:deenora/features/Azkar/azkar_model/azekr_category.dart';
import 'package:deenora/features/Azkar/azkar_model/azkar_model.dart';
import 'package:deenora/features/Quran/reading/models/ayah_model.dart';
import 'package:deenora/features/Quran/reading/models/surah_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AyahModelAdapter());
    registerAdapter(AzekrCategoryAdapter());
    registerAdapter(AzkarModelAdapter());
    registerAdapter(SurahModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AyahModelAdapter());
    registerAdapter(AzekrCategoryAdapter());
    registerAdapter(AzkarModelAdapter());
    registerAdapter(SurahModelAdapter());
  }
}
